name: jobify

services:

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=polls
    networks:
      - jobify-network
    volumes:
      - polls_pg_data:/postgres
    
  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    env_file:
      - ../backend/.env
    ports:
      - "5000:5000"
    networks:
      - jobify-network
  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - jobify-network


networks:
  jobify-network:
    driver: bridge

volumes:
  polls_pg_data:
